apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJwYXZhbmluZmluaXR5Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBFY21sMGFVQXhNak09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
